"""add_traveler_ncr_issue_log_witness_coc

Revision ID: 22c8f4876a90
Revises: 5c0d45b47184
Create Date: 2026-03-03 01:48:31.816781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22c8f4876a90'
down_revision: Union[str, None] = '5c0d45b47184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cocs',
    sa.Column('coc_id', sa.Integer(), nullable=False),
    sa.Column('wo_id', sa.Integer(), nullable=False),
    sa.Column('generated_date', sa.Date(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('export_format', sa.Enum('pdf', 'word', name='exportformat'), nullable=True),
    sa.Column('attachment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.wo_id'], ),
    sa.PrimaryKeyConstraint('coc_id'),
    sa.UniqueConstraint('wo_id', name='uq_coc_wo')
    )
    op.create_index(op.f('ix_cocs_coc_id'), 'cocs', ['coc_id'], unique=False)
    op.create_table('nonconformances',
    sa.Column('ncr_id', sa.Integer(), nullable=False),
    sa.Column('wo_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('opened_by', sa.Integer(), nullable=False),
    sa.Column('disposition', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_disposition', 'closed', name='ncrstatus'), nullable=False),
    sa.Column('resolution_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['opened_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.part_id'], ),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.wo_id'], ),
    sa.PrimaryKeyConstraint('ncr_id')
    )
    op.create_index(op.f('ix_nonconformances_ncr_id'), 'nonconformances', ['ncr_id'], unique=False)
    op.create_table('travelers',
    sa.Column('traveler_id', sa.Integer(), nullable=False),
    sa.Column('wo_id', sa.Integer(), nullable=False),
    sa.Column('work_plan_id', sa.Integer(), nullable=False),
    sa.Column('export_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'exported', 'scanned', name='travelerstatus'), nullable=False),
    sa.Column('scanned_upload_attachment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.wo_id'], ),
    sa.ForeignKeyConstraint(['work_plan_id'], ['work_plans.work_plan_id'], ),
    sa.PrimaryKeyConstraint('traveler_id')
    )
    op.create_index(op.f('ix_travelers_traveler_id'), 'travelers', ['traveler_id'], unique=False)
    op.create_table('witness_records',
    sa.Column('witness_id', sa.Integer(), nullable=False),
    sa.Column('wo_id', sa.Integer(), nullable=False),
    sa.Column('inspector_name', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('date_witnessed', sa.Date(), nullable=False),
    sa.Column('signed_document_attachment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.wo_id'], ),
    sa.PrimaryKeyConstraint('witness_id')
    )
    op.create_index(op.f('ix_witness_records_witness_id'), 'witness_records', ['witness_id'], unique=False)
    op.create_table('issue_logs',
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('wo_id', sa.Integer(), nullable=False),
    sa.Column('reported_by', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'closed', name='issuestatus'), nullable=False),
    sa.Column('ncr_id', sa.Integer(), nullable=True),
    sa.Column('customer_notified', sa.Boolean(), nullable=False),
    sa.Column('customer_response', sa.String(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ncr_id'], ['nonconformances.ncr_id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.wo_id'], ),
    sa.PrimaryKeyConstraint('issue_id')
    )
    op.create_index(op.f('ix_issue_logs_issue_id'), 'issue_logs', ['issue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issue_logs_issue_id'), table_name='issue_logs')
    op.drop_table('issue_logs')
    op.drop_index(op.f('ix_witness_records_witness_id'), table_name='witness_records')
    op.drop_table('witness_records')
    op.drop_index(op.f('ix_travelers_traveler_id'), table_name='travelers')
    op.drop_table('travelers')
    op.drop_index(op.f('ix_nonconformances_ncr_id'), table_name='nonconformances')
    op.drop_table('nonconformances')
    op.drop_index(op.f('ix_cocs_coc_id'), table_name='cocs')
    op.drop_table('cocs')
    # ### end Alembic commands ###
