"""initial_schema

Revision ID: 5c0d45b47184
Revises: 
Create Date: 2026-03-02 20:01:05.236716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c0d45b47184'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baths',
    sa.Column('bath_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('chemical', sa.String(), nullable=True),
    sa.Column('current_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('bath_id')
    )
    op.create_index(op.f('ix_baths_bath_id'), 'baths', ['bath_id'], unique=False)
    op.create_table('cleaning_procedures',
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'retired', name='procedurestatus'), nullable=False),
    sa.Column('document_number', sa.String(), nullable=True),
    sa.Column('spec_reference', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('procedure_id')
    )
    op.create_index(op.f('ix_cleaning_procedures_procedure_id'), 'cleaning_procedures', ['procedure_id'], unique=False)
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('itar_flag', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'ops_manager', 'sales_manager', 'qa_internal', 'quality_source', 'technician', 'shipping_receiving', name='userrole'), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('equipment_logs',
    sa.Column('equipment_log_id', sa.Integer(), nullable=False),
    sa.Column('bath_id', sa.Integer(), nullable=False),
    sa.Column('calibration_due', sa.Date(), nullable=True),
    sa.Column('certification_expiry', sa.Date(), nullable=True),
    sa.Column('maintenance_notes', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bath_id'], ['baths.bath_id'], ),
    sa.PrimaryKeyConstraint('equipment_log_id'),
    sa.UniqueConstraint('bath_id')
    )
    op.create_index(op.f('ix_equipment_logs_equipment_log_id'), 'equipment_logs', ['equipment_log_id'], unique=False)
    op.create_table('lab_maintenance_logs',
    sa.Column('lab_maintenance_id', sa.Integer(), nullable=False),
    sa.Column('bath_id', sa.Integer(), nullable=True),
    sa.Column('tech_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.Enum('titration', 'filter', 'sealer_check', name='tasktype'), nullable=False),
    sa.Column('date_performed', sa.Date(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('next_due', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['bath_id'], ['baths.bath_id'], ),
    sa.ForeignKeyConstraint(['tech_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('lab_maintenance_id')
    )
    op.create_index(op.f('ix_lab_maintenance_logs_lab_maintenance_id'), 'lab_maintenance_logs', ['lab_maintenance_id'], unique=False)
    op.create_table('parts',
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('spec', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('part_id')
    )
    op.create_index(op.f('ix_parts_part_id'), 'parts', ['part_id'], unique=False)
    op.create_table('procedure_version_history',
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.String(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('change_summary', sa.String(), nullable=True),
    sa.Column('archived_date', sa.Date(), nullable=False),
    sa.Column('previous_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['previous_version_id'], ['procedure_version_history.version_id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['cleaning_procedures.procedure_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index(op.f('ix_procedure_version_history_version_id'), 'procedure_version_history', ['version_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'partially_received', 'received', 'in_progress', 'on_hold', 'complete', 'shipped', 'cancelled', name='postatus'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('po_id')
    )
    op.create_index(op.f('ix_purchase_orders_po_id'), 'purchase_orders', ['po_id'], unique=False)
    op.create_table('tech_certifications',
    sa.Column('cert_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('authorized_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('authorized_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['authorized_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['cleaning_procedures.procedure_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('cert_id')
    )
    op.create_index(op.f('ix_tech_certifications_cert_id'), 'tech_certifications', ['cert_id'], unique=False)
    op.create_table('work_plans',
    sa.Column('work_plan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('work_plan_id')
    )
    op.create_index(op.f('ix_work_plans_work_plan_id'), 'work_plans', ['work_plan_id'], unique=False)
    op.create_table('intake_records',
    sa.Column('intake_id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('received_qty', sa.Integer(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('discrepancy_flag', sa.Boolean(), nullable=False),
    sa.Column('tech_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.po_id'], ),
    sa.ForeignKeyConstraint(['tech_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('intake_id')
    )
    op.create_index(op.f('ix_intake_records_intake_id'), 'intake_records', ['intake_id'], unique=False)
    op.create_table('section_groups',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('work_plan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['work_plan_id'], ['work_plans.work_plan_id'], ),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_index(op.f('ix_section_groups_section_id'), 'section_groups', ['section_id'], unique=False)
    op.create_table('tag_templates',
    sa.Column('tag_template_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('template_layout', sa.Text(), nullable=True),
    sa.Column('fields_required', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.part_id'], ),
    sa.PrimaryKeyConstraint('tag_template_id')
    )
    op.create_index(op.f('ix_tag_templates_tag_template_id'), 'tag_templates', ['tag_template_id'], unique=False)
    op.create_table('work_orders',
    sa.Column('wo_id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('work_plan_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('received', 'intake_po_verification', 'customer_outreach_hold', 'in_queue', 'pre_clean', 'final_clean', 'first_packaging', 'final_packaging', 'final_buyoff', 'coc_generation', 'shipped', 'ncr_hold', 'qa_rejection', name='wostatus'), nullable=False),
    sa.Column('priority_level', sa.Enum('normal', 'expedite', 'hold', name='wopriority'), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.part_id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.po_id'], ),
    sa.ForeignKeyConstraint(['work_plan_id'], ['work_plans.work_plan_id'], ),
    sa.PrimaryKeyConstraint('wo_id')
    )
    op.create_index(op.f('ix_work_orders_wo_id'), 'work_orders', ['wo_id'], unique=False)
    op.create_table('work_plan_procedures',
    sa.Column('work_plan_id', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['procedure_id'], ['cleaning_procedures.procedure_id'], ),
    sa.ForeignKeyConstraint(['work_plan_id'], ['work_plans.work_plan_id'], ),
    sa.PrimaryKeyConstraint('work_plan_id', 'procedure_id')
    )
    op.create_table('queue_priority_flags',
    sa.Column('priority_flag_id', sa.Integer(), nullable=False),
    sa.Column('wo_id', sa.Integer(), nullable=False),
    sa.Column('priority_level', sa.Enum('normal', 'expedite', 'hold', name='prioritylevel'), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('set_by', sa.Integer(), nullable=False),
    sa.Column('set_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['set_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.wo_id'], ),
    sa.PrimaryKeyConstraint('priority_flag_id'),
    sa.UniqueConstraint('wo_id', name='uq_queue_priority_flag_wo')
    )
    op.create_index(op.f('ix_queue_priority_flags_priority_flag_id'), 'queue_priority_flags', ['priority_flag_id'], unique=False)
    op.create_table('steps',
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('sequence_order', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('spec_reference', sa.String(), nullable=True),
    sa.Column('requires_authorization', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['procedure_id'], ['cleaning_procedures.procedure_id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section_groups.section_id'], ),
    sa.PrimaryKeyConstraint('step_id')
    )
    op.create_index(op.f('ix_steps_step_id'), 'steps', ['step_id'], unique=False)
    op.create_table('step_assignments',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('wo_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('tech_id', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('handoff_to', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['handoff_to'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['steps.step_id'], ),
    sa.ForeignKeyConstraint(['tech_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.wo_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_index(op.f('ix_step_assignments_assignment_id'), 'step_assignments', ['assignment_id'], unique=False)
    op.create_table('step_field_definitions',
    sa.Column('step_field_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('field_type', sa.Enum('text', 'number', 'checkbox_group', 'dropdown', 'table', name='fieldtype'), nullable=False),
    sa.Column('field_label', sa.String(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('spec_limit_low', sa.Float(), nullable=True),
    sa.Column('spec_limit_high', sa.Float(), nullable=True),
    sa.Column('table_columns', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['step_id'], ['steps.step_id'], ),
    sa.PrimaryKeyConstraint('step_field_id')
    )
    op.create_index(op.f('ix_step_field_definitions_step_field_id'), 'step_field_definitions', ['step_field_id'], unique=False)
    op.create_table('substeps',
    sa.Column('substep_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('instruction_text', sa.String(), nullable=False),
    sa.Column('warning_flag', sa.Boolean(), nullable=False),
    sa.Column('image_attachment', sa.String(), nullable=True),
    sa.Column('requires_signoff', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['steps.step_id'], ),
    sa.PrimaryKeyConstraint('substep_id')
    )
    op.create_index(op.f('ix_substeps_substep_id'), 'substeps', ['substep_id'], unique=False)
    op.create_table('time_logs',
    sa.Column('time_log_id', sa.Integer(), nullable=False),
    sa.Column('wo_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('tech_id', sa.Integer(), nullable=False),
    sa.Column('clock_in', sa.DateTime(), nullable=False),
    sa.Column('clock_out', sa.DateTime(), nullable=True),
    sa.Column('handoff_to', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['handoff_to'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['steps.step_id'], ),
    sa.ForeignKeyConstraint(['tech_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.wo_id'], ),
    sa.PrimaryKeyConstraint('time_log_id')
    )
    op.create_index(op.f('ix_time_logs_time_log_id'), 'time_logs', ['time_log_id'], unique=False)
    op.create_table('instruction_flags',
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('substep_id', sa.Integer(), nullable=False),
    sa.Column('reported_by', sa.Integer(), nullable=False),
    sa.Column('flag_type', sa.Enum('unclear', 'better_method', 'caused_issue', name='flagtype'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('open', 'reviewed', 'actioned', name='flagstatus'), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['reported_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['substep_id'], ['substeps.substep_id'], ),
    sa.PrimaryKeyConstraint('flag_id')
    )
    op.create_index(op.f('ix_instruction_flags_flag_id'), 'instruction_flags', ['flag_id'], unique=False)
    op.create_table('records',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('wo_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('substep_id', sa.Integer(), nullable=True),
    sa.Column('bath_id', sa.Integer(), nullable=True),
    sa.Column('tech_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('signoff', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bath_id'], ['baths.bath_id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['steps.step_id'], ),
    sa.ForeignKeyConstraint(['substep_id'], ['substeps.substep_id'], ),
    sa.ForeignKeyConstraint(['tech_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.wo_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_records_record_id'), 'records', ['record_id'], unique=False)
    op.create_table('step_field_entries',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('step_field_id', sa.Integer(), nullable=False),
    sa.Column('entered_value', sa.String(), nullable=True),
    sa.Column('out_of_spec', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records.record_id'], ),
    sa.ForeignKeyConstraint(['step_field_id'], ['step_field_definitions.step_field_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_index(op.f('ix_step_field_entries_entry_id'), 'step_field_entries', ['entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_step_field_entries_entry_id'), table_name='step_field_entries')
    op.drop_table('step_field_entries')
    op.drop_index(op.f('ix_records_record_id'), table_name='records')
    op.drop_table('records')
    op.drop_index(op.f('ix_instruction_flags_flag_id'), table_name='instruction_flags')
    op.drop_table('instruction_flags')
    op.drop_index(op.f('ix_time_logs_time_log_id'), table_name='time_logs')
    op.drop_table('time_logs')
    op.drop_index(op.f('ix_substeps_substep_id'), table_name='substeps')
    op.drop_table('substeps')
    op.drop_index(op.f('ix_step_field_definitions_step_field_id'), table_name='step_field_definitions')
    op.drop_table('step_field_definitions')
    op.drop_index(op.f('ix_step_assignments_assignment_id'), table_name='step_assignments')
    op.drop_table('step_assignments')
    op.drop_index(op.f('ix_steps_step_id'), table_name='steps')
    op.drop_table('steps')
    op.drop_index(op.f('ix_queue_priority_flags_priority_flag_id'), table_name='queue_priority_flags')
    op.drop_table('queue_priority_flags')
    op.drop_table('work_plan_procedures')
    op.drop_index(op.f('ix_work_orders_wo_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_tag_templates_tag_template_id'), table_name='tag_templates')
    op.drop_table('tag_templates')
    op.drop_index(op.f('ix_section_groups_section_id'), table_name='section_groups')
    op.drop_table('section_groups')
    op.drop_index(op.f('ix_intake_records_intake_id'), table_name='intake_records')
    op.drop_table('intake_records')
    op.drop_index(op.f('ix_work_plans_work_plan_id'), table_name='work_plans')
    op.drop_table('work_plans')
    op.drop_index(op.f('ix_tech_certifications_cert_id'), table_name='tech_certifications')
    op.drop_table('tech_certifications')
    op.drop_index(op.f('ix_purchase_orders_po_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_procedure_version_history_version_id'), table_name='procedure_version_history')
    op.drop_table('procedure_version_history')
    op.drop_index(op.f('ix_parts_part_id'), table_name='parts')
    op.drop_table('parts')
    op.drop_index(op.f('ix_lab_maintenance_logs_lab_maintenance_id'), table_name='lab_maintenance_logs')
    op.drop_table('lab_maintenance_logs')
    op.drop_index(op.f('ix_equipment_logs_equipment_log_id'), table_name='equipment_logs')
    op.drop_table('equipment_logs')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_cleaning_procedures_procedure_id'), table_name='cleaning_procedures')
    op.drop_table('cleaning_procedures')
    op.drop_index(op.f('ix_baths_bath_id'), table_name='baths')
    op.drop_table('baths')
    # ### end Alembic commands ###
